package:
  name: openms
  version: "2.0.1"
source:
  fn: OpenMS-2.0.1-src-contrib-docu.tar.gz
  url: https://github.com/OpenMS/OpenMS/releases/download/Release2.0.1/OpenMS-2.0.1-src-contrib-docu.tar.gz
build:
    number: 0
requirements:
  build:
    - gcc    # [linux]
    - llvm   # [osx]
    - cmake
    - wget
    - autoconf
    - automake
    - libtool
  run:
    
test:
  commands:
    - FileMerger
about:
  home: https://github.com/OpenMS/OpenMS
  license: BSD
  summary: OpenMS is an open-source software C++ library for LC-MS data management and analyses
